# Do not change any values in this file
server:
  port: ${PORT:8080}

spring:
  datasource:
    hikari:
      maxLifetime: "1800000"
      connectionTimeout: "30000"
      idleTimeout: "600000"
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    default: "local"

logging:
  level:
    org.springframework: OFF
    org.apache: OFF

security:
  allowed:
    domains: ${ALLOWED_DOMAINS}

info:
  name: Hydroponics REST Api
  license:
    type: MIT License
    url: https://github.com/hydroponics-system/hydro-api-microservice/blob/master/LICENSE.md
  version: Snapshot
  contact:
    name: Sam Butler
    email: sambutler1017@icloud.com
    url: https://github.com/hydroponics-system/hydro-api-microservice
  description: Restful API's for managing a hydroponic system.
